version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    restart: always
